import { chromium } from "/home/claude/.npm-global/lib/node_modules/playwright/index.mjs";
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto("http://127.0.0.1:5480/lloyds-bank-statement-to-csv", { waitUntil: "networkidle" });
console.log("Title:", await page.title());
const bodyText = await page.locator("body").innerText();
console.log("Has H1 content:", bodyText.includes("Lloyds Bank statement to CSV"));
console.log("Has 150 transaction cap mention:", bodyText.includes("150"));
console.log("Has proof of address FAQ:", bodyText.includes("proof of address"));
console.log("Has FAQPage schema:", (await page.content()).includes("FAQPage"));
await browser.close();
